const languages = [
  {
    name: "ABAP",
    type: "programming",
    extensions: [".abap"],
  },
  {
    name: "AGS Script",
    type: "programming",
    extensions: [".asc", ".ash"],
  },
  {
    name: "AMPL",
    type: "programming",
    extensions: [".ampl", ".mod"],
  },
  {
    name: "ANTLR",
    type: "programming",
    extensions: [".g4"],
  },
  {
    name: "APL",
    type: "programming",
    extensions: [".apl", ".dyalog"],
  },
  {
    name: "ASP",
    type: "programming",
    extensions: [".asp", ".asax", ".ascx", ".ashx", ".asmx", ".aspx", ".axd"],
  },
  {
    name: "ATS",
    type: "programming",
    extensions: [".dats", ".hats", ".sats"],
  },
  {
    name: "ActionScript",
    type: "programming",
    extensions: [".as"],
  },
  {
    name: "Ada",
    type: "programming",
    extensions: [".adb", ".ada", ".ads"],
  },
  {
    name: "Agda",
    type: "programming",
    extensions: [".agda"],
  },
  {
    name: "Alloy",
    type: "programming",
    extensions: [".als"],
  },
  {
    name: "Apex",
    type: "programming",
    extensions: [".cls"],
  },
  {
    name: "AppleScript",
    type: "programming",
    extensions: [".applescript", ".scpt"],
  },
  {
    name: "Arc",
    type: "programming",
    extensions: [".arc"],
  },
  {
    name: "Arduino",
    type: "programming",
    extensions: [".ino"],
  },
  {
    name: "AspectJ",
    type: "programming",
    extensions: [".aj"],
  },
  {
    name: "Assembly",
    type: "programming",
    extensions: [".asm", ".a51", ".inc", ".nasm"],
  },
  {
    name: "Augeas",
    type: "programming",
    extensions: [".aug"],
  },
  {
    name: "AutoHotkey",
    type: "programming",
    extensions: [".ahk", ".ahkl"],
  },
  {
    name: "AutoIt",
    type: "programming",
    extensions: [".au3"],
  },
  {
    name: "Awk",
    type: "programming",
    extensions: [".awk", ".auk", ".gawk", ".mawk", ".nawk"],
  },
  {
    name: "Batchfile",
    type: "programming",
    extensions: [".bat", ".cmd"],
  },
  {
    name: "Befunge",
    type: "programming",
    extensions: [".befunge"],
  },
  {
    name: "Bison",
    type: "programming",
    extensions: [".bison"],
  },
  {
    name: "BitBake",
    type: "programming",
    extensions: [".bb"],
  },
  {
    name: "BlitzBasic",
    type: "programming",
    extensions: [".bb", ".decls"],
  },
  {
    name: "BlitzMax",
    type: "programming",
    extensions: [".bmx"],
  },
  {
    name: "Bluespec",
    type: "programming",
    extensions: [".bsv"],
  },
  {
    name: "Boo",
    type: "programming",
    extensions: [".boo"],
  },
  {
    name: "Brainfuck",
    type: "programming",
    extensions: [".b", ".bf"],
  },
  {
    name: "Brightscript",
    type: "programming",
    extensions: [".brs"],
  },
  {
    name: "Bro",
    type: "programming",
    extensions: [".bro"],
  },
  {
    name: "C",
    type: "programming",
    extensions: [".c", ".cats", ".h", ".idc", ".w"],
  },
  {
    name: "C#",
    type: "programming",
    extensions: [".cs", ".cake", ".cshtml", ".csx"],
  },
  {
    name: "C++",
    type: "programming",
    extensions: [
      ".cpp",
      ".c++",
      ".cc",
      ".cp",
      ".cxx",
      ".h",
      ".h++",
      ".hh",
      ".hpp",
      ".hxx",
      ".inc",
      ".inl",
      ".ipp",
      ".tcc",
      ".tpp",
    ],
  },
  {
    name: "C2hs Haskell",
    type: "programming",
    extensions: [".chs"],
  },
  {
    name: "CLIPS",
    type: "programming",
    extensions: [".clp"],
  },
  {
    name: "CMake",
    type: "programming",
    extensions: [".cmake", ".cmake.in"],
  },
  {
    name: "COBOL",
    type: "programming",
    extensions: [".cob", ".cbl", ".ccp", ".cobol", ".cpy"],
  },
  {
    name: "Cap'n Proto",
    type: "programming",
    extensions: [".capnp"],
  },
  {
    name: "CartoCSS",
    type: "programming",
    extensions: [".mss"],
  },
  {
    name: "Ceylon",
    type: "programming",
    extensions: [".ceylon"],
  },
  {
    name: "Chapel",
    type: "programming",
    extensions: [".chpl"],
  },
  {
    name: "Charity",
    type: "programming",
    extensions: [".ch"],
  },
  {
    name: "ChucK",
    type: "programming",
    extensions: [".ck"],
  },
  {
    name: "Cirru",
    type: "programming",
    extensions: [".cirru"],
  },
  {
    name: "Clarion",
    type: "programming",
    extensions: [".clw"],
  },
  {
    name: "Clean",
    type: "programming",
    extensions: [".icl", ".dcl"],
  },
  {
    name: "Click",
    type: "programming",
    extensions: [".click"],
  },
  {
    name: "Clojure",
    type: "programming",
    extensions: [
      ".clj",
      ".boot",
      ".cl2",
      ".cljc",
      ".cljs",
      ".cljs.hl",
      ".cljscm",
      ".cljx",
      ".hic",
    ],
  },
  {
    name: "CoffeeScript",
    type: "programming",
    extensions: [".coffee", "._coffee", ".cake", ".cjsx", ".cson", ".iced"],
  },
  {
    name: "ColdFusion",
    type: "programming",
    extensions: [".cfm", ".cfml"],
  },
  {
    name: "ColdFusion CFC",
    type: "programming",
    extensions: [".cfc"],
  },
  {
    name: "Common Lisp",
    type: "programming",
    extensions: [
      ".lisp",
      ".asd",
      ".cl",
      ".l",
      ".lsp",
      ".ny",
      ".podsl",
      ".sexp",
    ],
  },
  {
    name: "Component Pascal",
    type: "programming",
    extensions: [".cp", ".cps"],
  },
  {
    name: "Cool",
    type: "programming",
    extensions: [".cl"],
  },
  {
    name: "Coq",
    type: "programming",
    extensions: [".coq", ".v"],
  },
  {
    name: "Crystal",
    type: "programming",
    extensions: [".cr"],
  },
  {
    name: "CSS",
    type: "programming",
    extensions: [".css"],
  },
  {
    name: "Cucumber",
    type: "programming",
    extensions: [".feature"],
  },
  {
    name: "Cuda",
    type: "programming",
    extensions: [".cu", ".cuh"],
  },
  {
    name: "Cycript",
    type: "programming",
    extensions: [".cy"],
  },
  {
    name: "Cython",
    type: "programming",
    extensions: [".pyx", ".pxd", ".pxi"],
  },
  {
    name: "D",
    type: "programming",
    extensions: [".d", ".di"],
  },
  {
    name: "DIGITAL Command Language",
    type: "programming",
    extensions: [".com"],
  },
  {
    name: "DM",
    type: "programming",
    extensions: [".dm"],
  },
  {
    name: "DTrace",
    type: "programming",
    extensions: [".d"],
  },
  {
    name: "Dart",
    type: "programming",
    extensions: [".dart"],
  },
  {
    name: "Dogescript",
    type: "programming",
    extensions: [".djs"],
  },
  {
    name: "Dylan",
    type: "programming",
    extensions: [".dylan", ".dyl", ".intr", ".lid"],
  },
  {
    name: "E",
    type: "programming",
    extensions: [".E"],
  },
  {
    name: "ECL",
    type: "programming",
    extensions: [".ecl", ".eclxml"],
  },
  {
    name: "ECLiPSe",
    type: "programming",
    extensions: [".ecl"],
  },
  {
    name: "Eiffel",
    type: "programming",
    extensions: [".e"],
  },
  {
    name: "Elixir",
    type: "programming",
    extensions: [".ex", ".exs"],
  },
  {
    name: "Elm",
    type: "programming",
    extensions: [".elm"],
  },
  {
    name: "Emacs Lisp",
    type: "programming",
    extensions: [".el", ".emacs", ".emacs.desktop"],
  },
  {
    name: "EmberScript",
    type: "programming",
    extensions: [".em", ".emberscript"],
  },
  {
    name: "Erlang",
    type: "programming",
    extensions: [".erl", ".es", ".escript", ".hrl", ".xrl", ".yrl"],
  },
  {
    name: "F#",
    type: "programming",
    extensions: [".fs", ".fsi", ".fsx"],
  },
  {
    name: "FLUX",
    type: "programming",
    extensions: [".fx", ".flux"],
  },
  {
    name: "FORTRAN",
    type: "programming",
    extensions: [".f90", ".f", ".f03", ".f08", ".f77", ".f95", ".for", ".fpp"],
  },
  {
    name: "Factor",
    type: "programming",
    extensions: [".factor"],
  },
  {
    name: "Fancy",
    type: "programming",
    extensions: [".fy", ".fancypack"],
  },
  {
    name: "Fantom",
    type: "programming",
    extensions: [".fan"],
  },
  {
    name: "Filterscript",
    type: "programming",
    extensions: [".fs"],
  },
  {
    name: "Forth",
    type: "programming",
    extensions: [".fth", ".4th", ".f", ".for", ".forth", ".fr", ".frt", ".fs"],
  },
  {
    name: "FreeMarker",
    type: "programming",
    extensions: [".ftl"],
  },
  {
    name: "Frege",
    type: "programming",
    extensions: [".fr"],
  },
  {
    name: "GAMS",
    type: "programming",
    extensions: [".gms"],
  },
  {
    name: "GAP",
    type: "programming",
    extensions: [".g", ".gap", ".gd", ".gi", ".tst"],
  },
  {
    name: "GAS",
    type: "programming",
    extensions: [".s", ".ms"],
  },
  {
    name: "GDScript",
    type: "programming",
    extensions: [".gd"],
  },
  {
    name: "GLSL",
    type: "programming",
    extensions: [
      ".glsl",
      ".fp",
      ".frag",
      ".frg",
      ".fs",
      ".fsh",
      ".fshader",
      ".geo",
      ".geom",
      ".glslv",
      ".gshader",
      ".shader",
      ".vert",
      ".vrx",
      ".vsh",
      ".vshader",
    ],
  },
  {
    name: "Game Maker Language",
    type: "programming",
    extensions: [".gml"],
  },
  {
    name: "Genshi",
    type: "programming",
    extensions: [".kid"],
  },
  {
    name: "Gentoo Ebuild",
    type: "programming",
    extensions: [".ebuild"],
  },
  {
    name: "Gentoo Eclass",
    type: "programming",
    extensions: [".eclass"],
  },
  {
    name: "Glyph",
    type: "programming",
    extensions: [".glf"],
  },
  {
    name: "Gnuplot",
    type: "programming",
    extensions: [".gp", ".gnu", ".gnuplot", ".plot", ".plt"],
  },
  {
    name: "Go",
    type: "programming",
    extensions: [".go"],
  },
  {
    name: "Golo",
    type: "programming",
    extensions: [".golo"],
  },
  {
    name: "Gosu",
    type: "programming",
    extensions: [".gs", ".gst", ".gsx", ".vark"],
  },
  {
    name: "Grace",
    type: "programming",
    extensions: [".grace"],
  },
  {
    name: "Grammatical Framework",
    type: "programming",
    extensions: [".gf"],
  },
  {
    name: "Groovy",
    type: "programming",
    extensions: [".groovy", ".grt", ".gtpl", ".gvy"],
  },
  {
    name: "Groovy Server Pages",
    type: "programming",
    extensions: [".gsp"],
  },
  {
    name: "HCL",
    type: "programming",
    extensions: [".hcl", ".tf"],
  },
  {
    name: "HLSL",
    type: "programming",
    extensions: [".hlsl", ".fx", ".fxh", ".hlsli"],
  },
  {
    name: "Hack",
    type: "programming",
    extensions: [".hh", ".php"],
  },
  {
    name: "Harbour",
    type: "programming",
    extensions: [".hb"],
  },
  {
    name: "Haskell",
    type: "programming",
    extensions: [".hs", ".hsc"],
  },
  {
    name: "Haxe",
    type: "programming",
    extensions: [".hx", ".hxsl"],
  },
  {
    name: "HTML",
    type: "programming",
    extensions: [".html", ".htm"],
  },
  {
    name: "Hy",
    type: "programming",
    extensions: [".hy"],
  },
  {
    name: "HyPhy",
    type: "programming",
    extensions: [".bf"],
  },
  {
    name: "IDL",
    type: "programming",
    extensions: [".pro", ".dlm"],
  },
  {
    name: "IGOR Pro",
    type: "programming",
    extensions: [".ipf"],
  },
  {
    name: "Idris",
    type: "programming",
    extensions: [".idr", ".lidr"],
  },
  {
    name: "Inform 7",
    type: "programming",
    extensions: [".ni", ".i7x"],
  },
  {
    name: "Inno Setup",
    type: "programming",
    extensions: [".iss"],
  },
  {
    name: "Io",
    type: "programming",
    extensions: [".io"],
  },
  {
    name: "Ioke",
    type: "programming",
    extensions: [".ik"],
  },
  {
    name: "Isabelle",
    type: "programming",
    extensions: [".thy"],
  },
  {
    name: "J",
    type: "programming",
    extensions: [".ijs"],
  },
  {
    name: "JFlex",
    type: "programming",
    extensions: [".flex", ".jflex"],
  },
  {
    name: "JSONiq",
    type: "programming",
    extensions: [".jq"],
  },
  {
    name: "JSX",
    type: "programming",
    extensions: [".jsx"],
  },
  {
    name: "Jasmin",
    type: "programming",
    extensions: [".j"],
  },
  {
    name: "Java",
    type: "programming",
    extensions: [".java"],
  },
  {
    name: "Java Server Pages",
    type: "programming",
    extensions: [".jsp"],
  },
  {
    name: "JavaScript",
    type: "programming",
    extensions: [
      ".js",
      "._js",
      ".bones",
      ".es",
      ".es6",
      ".frag",
      ".gs",
      ".jake",
      ".jsb",
      ".jscad",
      ".jsfl",
      ".jsm",
      ".jss",
      ".njs",
      ".pac",
      ".sjs",
      ".ssjs",
      ".sublime-build",
      ".sublime-commands",
      ".sublime-completions",
      ".sublime-keymap",
      ".sublime-macro",
      ".sublime-menu",
      ".sublime-mousemap",
      ".sublime-project",
      ".sublime-settings",
      ".sublime-theme",
      ".sublime-workspace",
      ".sublime_metrics",
      ".sublime_session",
      ".xsjs",
      ".xsjslib",
    ],
  },
  {
    name: "Julia",
    type: "programming",
    extensions: [".jl"],
  },
  {
    name: "KRL",
    type: "programming",
    extensions: [".krl"],
  },
  {
    name: "KiCad",
    type: "programming",
    extensions: [".sch", ".brd", ".kicad_pcb"],
  },
  {
    name: "Kotlin",
    type: "programming",
    extensions: [".kt", ".ktm", ".kts"],
  },
  {
    name: "LFE",
    type: "programming",
    extensions: [".lfe"],
  },
  {
    name: "LLVM",
    type: "programming",
    extensions: [".ll"],
  },
  {
    name: "LOLCODE",
    type: "programming",
    extensions: [".lol"],
  },
  {
    name: "LSL",
    type: "programming",
    extensions: [".lsl", ".lslp"],
  },
  {
    name: "LabVIEW",
    type: "programming",
    extensions: [".lvproj"],
  },
  {
    name: "Lasso",
    type: "programming",
    extensions: [".lasso", ".las", ".lasso8", ".lasso9", ".ldml"],
  },
  {
    name: "Lean",
    type: "programming",
    extensions: [".lean", ".hlean"],
  },
  {
    name: "Lex",
    type: "programming",
    extensions: [".l", ".lex"],
  },
  {
    name: "LilyPond",
    type: "programming",
    extensions: [".ly", ".ily"],
  },
  {
    name: "Limbo",
    type: "programming",
    extensions: [".b", ".m"],
  },
  {
    name: "Literate Agda",
    type: "programming",
    extensions: [".lagda"],
  },
  {
    name: "Literate CoffeeScript",
    type: "programming",
    extensions: [".litcoffee"],
  },
  {
    name: "Literate Haskell",
    type: "programming",
    extensions: [".lhs"],
  },
  {
    name: "LiveScript",
    type: "programming",
    extensions: [".ls", "._ls"],
  },
  {
    name: "Logos",
    type: "programming",
    extensions: [".xm", ".x", ".xi"],
  },
  {
    name: "Logtalk",
    type: "programming",
    extensions: [".lgt", ".logtalk"],
  },
  {
    name: "LookML",
    type: "programming",
    extensions: [".lookml"],
  },
  {
    name: "LoomScript",
    type: "programming",
    extensions: [".ls"],
  },
  {
    name: "Lua",
    type: "programming",
    extensions: [".lua", ".fcgi", ".nse", ".pd_lua", ".rbxs", ".wlua"],
  },
  {
    name: "M",
    type: "programming",
    extensions: [".mumps", ".m"],
  },
  {
    name: "M4",
    type: "programming",
    extensions: [".m4"],
  },
  {
    name: "M4Sugar",
    type: "programming",
    extensions: [".m4"],
  },
  {
    name: "MAXScript",
    type: "programming",
    extensions: [".ms", ".mcr"],
  },
  {
    name: "MUF",
    type: "programming",
    extensions: [".muf", ".m"],
  },
  {
    name: "Makefile",
    type: "programming",
    extensions: [".mak", ".d", ".mk", ".mkfile"],
  },
  {
    name: "Mako",
    type: "programming",
    extensions: [".mako", ".mao"],
  },
  {
    name: "Mathematica",
    type: "programming",
    extensions: [
      ".mathematica",
      ".cdf",
      ".m",
      ".ma",
      ".mt",
      ".nb",
      ".nbp",
      ".wl",
      ".wlt",
    ],
  },
  {
    name: "Matlab",
    type: "programming",
    extensions: [".matlab", ".m"],
  },
  {
    name: "Mercury",
    type: "programming",
    extensions: [".m", ".moo"],
  },
  {
    name: "Metal",
    type: "programming",
    extensions: [".metal"],
  },
  {
    name: "MiniD",
    type: "programming",
    extensions: [".minid"],
  },
  {
    name: "Mirah",
    type: "programming",
    extensions: [".druby", ".duby", ".mir", ".mirah"],
  },
  {
    name: "Modelica",
    type: "programming",
    extensions: [".mo"],
  },
  {
    name: "Modula-2",
    type: "programming",
    extensions: [".mod"],
  },
  {
    name: "Module Management System",
    type: "programming",
    extensions: [".mms", ".mmk"],
  },
  {
    name: "Monkey",
    type: "programming",
    extensions: [".monkey"],
  },
  {
    name: "Moocode",
    type: "programming",
    extensions: [".moo"],
  },
  {
    name: "MoonScript",
    type: "programming",
    extensions: [".moon"],
  },
  {
    name: "Myghty",
    type: "programming",
    extensions: [".myt"],
  },
  {
    name: "NCL",
    type: "programming",
    extensions: [".ncl"],
  },
  {
    name: "NSIS",
    type: "programming",
    extensions: [".nsi", ".nsh"],
  },
  {
    name: "Nemerle",
    type: "programming",
    extensions: [".n"],
  },
  {
    name: "NetLinx",
    type: "programming",
    extensions: [".axs", ".axi"],
  },
  {
    name: "NetLinx+ERB",
    type: "programming",
    extensions: [".axs.erb", ".axi.erb"],
  },
  {
    name: "NetLogo",
    type: "programming",
    extensions: [".nlogo"],
  },
  {
    name: "NewLisp",
    type: "programming",
    extensions: [".nl", ".lisp", ".lsp"],
  },
  {
    name: "Nimrod",
    type: "programming",
    extensions: [".nim", ".nimrod"],
  },
  {
    name: "Nit",
    type: "programming",
    extensions: [".nit"],
  },
  {
    name: "Nix",
    type: "programming",
    extensions: [".nix"],
  },
  {
    name: "Nu",
    type: "programming",
    extensions: [".nu"],
  },
  {
    name: "NumPy",
    type: "programming",
    extensions: [".numpy", ".numpyw", ".numsc"],
  },
  {
    name: "OCaml",
    type: "programming",
    extensions: [".ml", ".eliom", ".eliomi", ".ml4", ".mli", ".mll", ".mly"],
  },
  {
    name: "Objective-C",
    type: "programming",
    extensions: [".m", ".h"],
  },
  {
    name: "Objective-C++",
    type: "programming",
    extensions: [".mm"],
  },
  {
    name: "Objective-J",
    type: "programming",
    extensions: [".j", ".sj"],
  },
  {
    name: "Omgrofl",
    type: "programming",
    extensions: [".omgrofl"],
  },
  {
    name: "Opa",
    type: "programming",
    extensions: [".opa"],
  },
  {
    name: "Opal",
    type: "programming",
    extensions: [".opal"],
  },
  {
    name: "OpenCL",
    type: "programming",
    extensions: [".cl", ".opencl"],
  },
  {
    name: "OpenEdge ABL",
    type: "programming",
    extensions: [".p", ".cls"],
  },
  {
    name: "OpenSCAD",
    type: "programming",
    extensions: [".scad"],
  },
  {
    name: "Ox",
    type: "programming",
    extensions: [".ox", ".oxh", ".oxo"],
  },
  {
    name: "Oxygene",
    type: "programming",
    extensions: [".oxygene"],
  },
  {
    name: "Oz",
    type: "programming",
    extensions: [".oz"],
  },
  {
    name: "PAWN",
    type: "programming",
    extensions: [".pwn", ".inc"],
  },
  {
    name: "PHP",
    type: "programming",
    extensions: [
      ".php",
      ".aw",
      ".ctp",
      ".fcgi",
      ".inc",
      ".php3",
      ".php4",
      ".php5",
      ".phps",
      ".phpt",
    ],
  },
  {
    name: "PLSQL",
    type: "programming",
    extensions: [".pls", ".pck", ".pkb", ".pks", ".plb", ".plsql", ".sql"],
  },
  {
    name: "PLpgSQL",
    type: "programming",
    extensions: [".sql"],
  },
  {
    name: "POV-Ray SDL",
    type: "programming",
    extensions: [".pov", ".inc"],
  },
  {
    name: "Pan",
    type: "programming",
    extensions: [".pan"],
  },
  {
    name: "Papyrus",
    type: "programming",
    extensions: [".psc"],
  },
  {
    name: "Parrot",
    type: "programming",
    extensions: [".parrot"],
  },
  {
    name: "Parrot Assembly",
    type: "programming",
    extensions: [".pasm"],
  },
  {
    name: "Parrot Internal Representation",
    type: "programming",
    extensions: [".pir"],
  },
  {
    name: "Pascal",
    type: "programming",
    extensions: [".pas", ".dfm", ".dpr", ".inc", ".lpr", ".pp"],
  },
  {
    name: "Perl",
    type: "programming",
    extensions: [
      ".pl",
      ".al",
      ".cgi",
      ".fcgi",
      ".perl",
      ".ph",
      ".plx",
      ".pm",
      ".pod",
      ".psgi",
      ".t",
    ],
  },
  {
    name: "Perl6",
    type: "programming",
    extensions: [
      ".6pl",
      ".6pm",
      ".nqp",
      ".p6",
      ".p6l",
      ".p6m",
      ".pl",
      ".pl6",
      ".pm",
      ".pm6",
      ".t",
    ],
  },
  {
    name: "PicoLisp",
    type: "programming",
    extensions: [".l"],
  },
  {
    name: "PigLatin",
    type: "programming",
    extensions: [".pig"],
  },
  {
    name: "Pike",
    type: "programming",
    extensions: [".pike", ".pmod"],
  },
  {
    name: "PogoScript",
    type: "programming",
    extensions: [".pogo"],
  },
  {
    name: "Pony",
    type: "programming",
    extensions: [".pony"],
  },
  {
    name: "PowerShell",
    type: "programming",
    extensions: [".ps1", ".psd1", ".psm1"],
  },
  {
    name: "Processing",
    type: "programming",
    extensions: [".pde"],
  },
  {
    name: "Prolog",
    type: "programming",
    extensions: [".pl", ".pro", ".prolog", ".yap"],
  },
  {
    name: "Propeller Spin",
    type: "programming",
    extensions: [".spin"],
  },
  {
    name: "Puppet",
    type: "programming",
    extensions: [".pp"],
  },
  {
    name: "Pure Data",
    type: "programming",
    extensions: [".pd"],
  },
  {
    name: "PureBasic",
    type: "programming",
    extensions: [".pb", ".pbi"],
  },
  {
    name: "PureScript",
    type: "programming",
    extensions: [".purs"],
  },
  {
    name: "Python",
    type: "programming",
    extensions: [
      ".py",
      ".bzl",
      ".cgi",
      ".fcgi",
      ".gyp",
      ".lmi",
      ".pyde",
      ".pyp",
      ".pyt",
      ".pyw",
      ".rpy",
      ".tac",
      ".wsgi",
      ".xpy",
    ],
  },
  {
    name: "QML",
    type: "programming",
    extensions: [".qml", ".qbs"],
  },
  {
    name: "QMake",
    type: "programming",
    extensions: [".pro", ".pri"],
  },
  {
    name: "R",
    type: "programming",
    extensions: [".r", ".rd", ".rsx"],
  },
  {
    name: "REALbasic",
    type: "programming",
    extensions: [
      ".rbbas",
      ".rbfrm",
      ".rbmnu",
      ".rbres",
      ".rbtbar",
      ".rbuistate",
    ],
  },
  {
    name: "Racket",
    type: "programming",
    extensions: [".rkt", ".rktd", ".rktl", ".scrbl"],
  },
  {
    name: "Ragel in Ruby Host",
    type: "programming",
    extensions: [".rl"],
  },
  {
    name: "Rebol",
    type: "programming",
    extensions: [".reb", ".r", ".r2", ".r3", ".rebol"],
  },
  {
    name: "Red",
    type: "programming",
    extensions: [".red", ".reds"],
  },
  {
    name: "Redcode",
    type: "programming",
    extensions: [".cw"],
  },
  {
    name: "Ren'Py",
    type: "programming",
    extensions: [".rpy"],
  },
  {
    name: "RenderScript",
    type: "programming",
    extensions: [".rs", ".rsh"],
  },
  {
    name: "RobotFramework",
    type: "programming",
    extensions: [".robot"],
  },
  {
    name: "Rouge",
    type: "programming",
    extensions: [".rg"],
  },
  {
    name: "Ruby",
    type: "programming",
    extensions: [
      ".rb",
      ".builder",
      ".fcgi",
      ".gemspec",
      ".god",
      ".irbrc",
      ".jbuilder",
      ".mspec",
      ".pluginspec",
      ".podspec",
      ".rabl",
      ".rake",
      ".rbuild",
      ".rbw",
      ".rbx",
      ".ru",
      ".ruby",
      ".thor",
      ".watchr",
    ],
  },
  {
    name: "Rust",
    type: "programming",
    extensions: [".rs", ".rs.in"],
  },
  {
    name: "SAS",
    type: "programming",
    extensions: [".sas"],
  },
  {
    name: "SMT",
    type: "programming",
    extensions: [".smt2", ".smt"],
  },
  {
    name: "SQF",
    type: "programming",
    extensions: [".sqf", ".hqf"],
  },
  {
    name: "SQLPL",
    type: "programming",
    extensions: [".sql", ".db2"],
  },
  {
    name: "Sage",
    type: "programming",
    extensions: [".sage", ".sagews"],
  },
  {
    name: "SaltStack",
    type: "programming",
    extensions: [".sls"],
  },
  {
    name: "Scala",
    type: "programming",
    extensions: [".scala", ".sbt", ".sc"],
  },
  {
    name: "Scheme",
    type: "programming",
    extensions: [".scm", ".sld", ".sls", ".sps", ".ss"],
  },
  {
    name: "Scilab",
    type: "programming",
    extensions: [".sci", ".sce", ".tst"],
  },
  {
    name: "Self",
    type: "programming",
    extensions: [".self"],
  },
  {
    name: "Shell",
    type: "programming",
    extensions: [
      ".sh",
      ".bash",
      ".bats",
      ".cgi",
      ".command",
      ".fcgi",
      ".ksh",
      ".sh.in",
      ".tmux",
      ".tool",
      ".zsh",
    ],
  },
  {
    name: "ShellSession",
    type: "programming",
    extensions: [".sh-session"],
  },
  {
    name: "Shen",
    type: "programming",
    extensions: [".shen"],
  },
  {
    name: "Slash",
    type: "programming",
    extensions: [".sl"],
  },
  {
    name: "Smali",
    type: "programming",
    extensions: [".smali"],
  },
  {
    name: "Smalltalk",
    type: "programming",
    extensions: [".st", ".cs"],
  },
  {
    name: "Smarty",
    type: "programming",
    extensions: [".tpl"],
  },
  {
    name: "SourcePawn",
    type: "programming",
    extensions: [".sp", ".inc", ".sma"],
  },
  {
    name: "Squirrel",
    type: "programming",
    extensions: [".nut"],
  },
  {
    name: "Stan",
    type: "programming",
    extensions: [".stan"],
  },
  {
    name: "Standard ML",
    type: "programming",
    extensions: [".ML", ".fun", ".sig", ".sml"],
  },
  {
    name: "Stata",
    type: "programming",
    extensions: [".do", ".ado", ".doh", ".ihlp", ".mata", ".matah", ".sthlp"],
  },
  {
    name: "SuperCollider",
    type: "programming",
    extensions: [".sc", ".scd"],
  },
  {
    name: "Swift",
    type: "programming",
    extensions: [".swift"],
  },
  {
    name: "SystemVerilog",
    type: "programming",
    extensions: [".sv", ".svh", ".vh"],
  },
  {
    name: "TXL",
    type: "programming",
    extensions: [".txl"],
  },
  {
    name: "Tcl",
    type: "programming",
    extensions: [".tcl", ".adp", ".tm"],
  },
  {
    name: "Tcsh",
    type: "programming",
    extensions: [".tcsh", ".csh"],
  },
  {
    name: "Terra",
    type: "programming",
    extensions: [".t"],
  },
  {
    name: "Thrift",
    type: "programming",
    extensions: [".thrift"],
  },
  {
    name: "Turing",
    type: "programming",
    extensions: [".t", ".tu"],
  },
  {
    name: "TypeScript",
    type: "programming",
    extensions: [".ts", ".tsx"],
  },
  {
    name: "Unified Parallel C",
    type: "programming",
    extensions: [".upc"],
  },
  {
    name: "Uno",
    type: "programming",
    extensions: [".uno"],
  },
  {
    name: "UnrealScript",
    type: "programming",
    extensions: [".uc"],
  },
  {
    name: "UrWeb",
    type: "programming",
    extensions: [".ur", ".urs"],
  },
  {
    name: "VCL",
    type: "programming",
    extensions: [".vcl"],
  },
  {
    name: "VHDL",
    type: "programming",
    extensions: [
      ".vhdl",
      ".vhd",
      ".vhf",
      ".vhi",
      ".vho",
      ".vhs",
      ".vht",
      ".vhw",
    ],
  },
  {
    name: "Vala",
    type: "programming",
    extensions: [".vala", ".vapi"],
  },
  {
    name: "Verilog",
    type: "programming",
    extensions: [".v", ".veo"],
  },
  {
    name: "VimL",
    type: "programming",
    extensions: [".vim"],
  },
  {
    name: "Visual Basic",
    type: "programming",
    extensions: [
      ".vb",
      ".bas",
      ".cls",
      ".frm",
      ".frx",
      ".vba",
      ".vbhtml",
      ".vbs",
    ],
  },
  {
    name: "Volt",
    type: "programming",
    extensions: [".volt"],
  },
  {
    name: "WebIDL",
    type: "programming",
    extensions: [".webidl"],
  },
  {
    name: "X10",
    type: "programming",
    extensions: [".x10"],
  },
  {
    name: "XC",
    type: "programming",
    extensions: [".xc"],
  },
  {
    name: "XPages",
    type: "programming",
    extensions: [".xsp-config", ".xsp.metadata"],
  },
  {
    name: "XProc",
    type: "programming",
    extensions: [".xpl", ".xproc"],
  },
  {
    name: "XQuery",
    type: "programming",
    extensions: [".xquery", ".xq", ".xql", ".xqm", ".xqy"],
  },
  {
    name: "XS",
    type: "programming",
    extensions: [".xs"],
  },
  {
    name: "XSLT",
    type: "programming",
    extensions: [".xslt", ".xsl"],
  },
  {
    name: "Xojo",
    type: "programming",
    extensions: [
      ".xojo_code",
      ".xojo_menu",
      ".xojo_report",
      ".xojo_script",
      ".xojo_toolbar",
      ".xojo_window",
    ],
  },
  {
    name: "Xtend",
    type: "programming",
    extensions: [".xtend"],
  },
  {
    name: "Yacc",
    type: "programming",
    extensions: [".y", ".yacc", ".yy"],
  },
  {
    name: "Zephir",
    type: "programming",
    extensions: [".zep"],
  },
  {
    name: "Zimpl",
    type: "programming",
    extensions: [".zimpl", ".zmpl", ".zpl"],
  },
  {
    name: "eC",
    type: "programming",
    extensions: [".ec", ".eh"],
  },
  {
    name: "fish",
    type: "programming",
    extensions: [".fish"],
  },
  {
    name: "mupad",
    type: "programming",
    extensions: [".mu"],
  },
  {
    name: "nesC",
    type: "programming",
    extensions: [".nc"],
  },
  {
    name: "ooc",
    type: "programming",
    extensions: [".ooc"],
  },
  {
    name: "wisp",
    type: "programming",
    extensions: [".wisp"],
  },
  {
    name: "xBase",
    type: "programming",
    extensions: [".prg", ".ch", ".prw"],
  },
];

// export the array
module.exports = languages;
